import type { HeaderBarItem } from '../shell/HeaderBar.js';
import { KeyboardEvent } from 'react';
export declare function useUserProfileSettingsController(): {
    currentUser: import("../../../common/types/context").CurrentUser;
    breadcrumbs: HeaderBarItem[];
    deleteOpen: boolean;
    isEditingName: boolean;
    draftName: string;
    nameInputRef: import("react").RefObject<HTMLInputElement | null>;
    isDeleting: boolean;
    isUpdatingUser: boolean;
    displayName: string;
    nameInitials: string;
    setDeleteOpen: import("react").Dispatch<import("react").SetStateAction<boolean>>;
    setDraftName: import("react").Dispatch<import("react").SetStateAction<string>>;
    handleDeleteAccount: () => void;
    handleStartEditingName: () => void;
    handleCancelEditingName: () => void;
    handleNameKeyDown: (event: KeyboardEvent<HTMLInputElement>) => void;
};
export type UserProfileSettingsViewModel = ReturnType<typeof useUserProfileSettingsController>;
