'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { publicConfig } from '@/config/json/public';
import { Sparkles } from 'lucide-react';
import Image from 'next/image';
import clipboardIllustration from '../../assets/clipboard.svg';
import mathSymbolsIllustration from '../../assets/math.svg';
export default function SignInLayout({ children }) {
    return (_jsxs("div", { className: "grid h-screen w-full grid-cols-2 gap-4 overflow-hidden p-4 lg:p-6 [@media(orientation:portrait)]:grid-cols-1 [@media(orientation:portrait)]:overflow-y-auto [@media(orientation:portrait)]:p-3 sm:[@media(orientation:portrait)]:p-4", children: [_jsxs("div", { className: "flex min-h-0 flex-col items-center justify-between overflow-hidden rounded-3xl px-6 pt-10 pb-6 text-center sm:px-8 lg:px-10 lg:pt-24 lg:pb-8 [@media(orientation:portrait)]:min-h-[14rem] [@media(orientation:portrait)]:px-5 [@media(orientation:portrait)]:pt-8 [@media(orientation:portrait)]:pb-6 sm:[@media(orientation:portrait)]:min-h-[18rem] sm:[@media(orientation:portrait)]:px-8 sm:[@media(orientation:portrait)]:pt-12", style: {
                    background: 'radial-gradient(circle, #1395E1 0%, #93D0F3 70%)',
                }, children: [_jsxs("div", { className: "flex w-full max-w-md flex-col gap-y-4", children: [_jsx("div", { className: "flex w-full justify-start", children: _jsx(Image, { src: clipboardIllustration, alt: "clipboard", width: 72, height: 72, className: "h-16 w-16 sm:h-[88px] sm:w-[88px] lg:h-[100px] lg:w-[100px]" }) }), _jsx("div", { className: "flex w-full justify-end", children: _jsx(Sparkles, { className: "size-6 text-white" }) }), _jsxs("h1", { className: "text-2xl font-medium text-white sm:text-3xl", children: ["Welcome to ", publicConfig.app.name] }), _jsx("p", { className: "text-sm leading-6 text-white sm:text-base", children: publicConfig.app.welcomeText })] }), _jsx("div", { className: "mt-6 flex w-full justify-start lg:mt-10", children: _jsx(Image, { src: mathSymbolsIllustration, alt: "math-symbols", width: 209, height: 209, loading: "eager", className: "h-24 w-24 sm:h-36 sm:w-36 lg:h-[209px] lg:w-[209px]" }) })] }), _jsx("div", { className: "grid place-items-center [@media(orientation:portrait)]:items-start", children: _jsx("div", { className: "w-full max-w-md [@media(orientation:portrait)]:rounded-3xl [@media(orientation:portrait)]:border [@media(orientation:portrait)]:border-sky-100 [@media(orientation:portrait)]:bg-white/90 [@media(orientation:portrait)]:p-5 [@media(orientation:portrait)]:shadow-sm sm:[@media(orientation:portrait)]:p-6", children: children }) })] }));
}
//# sourceMappingURL=SignInLayout.js.map