"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = SignInLayoutView;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const image_1 = __importDefault(require("next/image"));
function SignInLayoutView({ appDescription, appName, children, heroDecorationSrc = '/math-symbols.svg', heroLogoSrc = '/clipboard.svg', }) {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "grid min-h-screen w-full grid-cols-2 gap-4 overflow-hidden p-4 lg:p-6 [@media(orientation:portrait)]:grid-cols-1 [@media(orientation:portrait)]:grid-rows-[auto_1fr] [@media(orientation:portrait)]:overflow-y-auto [@media(orientation:portrait)]:p-3 sm:[@media(orientation:portrait)]:p-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex min-h-0 flex-col items-center justify-between overflow-hidden rounded-3xl px-6 pt-10 pb-6 text-center sm:px-8 lg:px-10 lg:pt-24 lg:pb-8 [@media(orientation:portrait)]:min-h-[14rem] [@media(orientation:portrait)]:justify-start [@media(orientation:portrait)]:gap-8 [@media(orientation:portrait)]:px-5 [@media(orientation:portrait)]:pt-8 [@media(orientation:portrait)]:pb-6 sm:[@media(orientation:portrait)]:min-h-[18rem] sm:[@media(orientation:portrait)]:px-8 sm:[@media(orientation:portrait)]:pt-12", style: {
                    background: 'radial-gradient(circle, #1395E1 0%, #93D0F3 70%)',
                }, children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex w-full max-w-md flex-col gap-y-4", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex w-full justify-start", children: (0, jsx_runtime_1.jsx)(image_1.default, { src: heroLogoSrc, alt: "clipboard", width: 72, height: 72, className: "h-16 w-16 sm:h-[88px] sm:w-[88px] lg:h-[100px] lg:w-[100px]" }) }), (0, jsx_runtime_1.jsx)("div", { className: "flex w-full justify-end", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Sparkles, { className: "size-6 text-white" }) }), (0, jsx_runtime_1.jsxs)("h1", { className: "text-2xl font-medium text-white sm:text-3xl", children: ["Welcome to ", appName] }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm leading-6 text-white sm:text-base", children: appDescription })] }), (0, jsx_runtime_1.jsx)("div", { className: "mt-6 flex w-full justify-start lg:mt-10 [@media(orientation:portrait)]:mt-0", children: (0, jsx_runtime_1.jsx)(image_1.default, { src: heroDecorationSrc, alt: "hero-decoration", width: 209, height: 209, className: "h-24 w-24 sm:h-36 sm:w-36 lg:h-[209px] lg:w-[209px]" }) })] }), (0, jsx_runtime_1.jsx)("div", { className: "grid place-items-center [@media(orientation:portrait)]:items-start [@media(orientation:portrait)]:pb-2", children: (0, jsx_runtime_1.jsx)("div", { className: "w-full max-w-md [@media(orientation:portrait)]:max-w-none [@media(orientation:portrait)]:rounded-3xl [@media(orientation:portrait)]:border [@media(orientation:portrait)]:border-sky-100 [@media(orientation:portrait)]:bg-white/90 [@media(orientation:portrait)]:p-5 [@media(orientation:portrait)]:shadow-sm sm:[@media(orientation:portrait)]:p-6", children: children }) })] }));
}
//# sourceMappingURL=SignInLayoutView.js.map